# theme: jekyll-theme-cayman

url: https://emkademy.com
name: Kıvanç Yüksel
description: Yerinde duran, geriye gidiyor demektir... İleri, daima ileri! - MKA
site_name: Emkademy
frame_image: "/assets/img/full_width_image.jpg"
host: 0.0.0.0
# avatar:

defaults:
    -
        scope:
            path: ""
            type: "kalkulus_oncesi"
        values:
            image: "/assets/img/kalkulus_oncesi/kalkulus_oncesi.jpg"
            collection_label: "Kalkulüs Öncesi"
            layout: "post"

collections:
    kalkulus_oncesi:
        title: Kalkülüs Öncesi
        permalink: /:collection/:title
        image: "/assets/img/kalkulus_oncesi/kalkulus_oncesi.jpg"
        output: true
    research:
        title: Research
        permalink: /:collection/:title
        output: true

plugins:
    - jemoji

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed
  load_paths:
      - _sass
      - mdb

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: kivancyy
  flickr:
  github: kivancyuksel
  instagram: kivancyuksell
  linkedin: kivanc-yuksel-6b7244150
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: kivanc_yuksel
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UC8QIX-TzWoF8CV9tgWYERqg
  googleplus: # anything in your profile username that comes after plus.google.com/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
