# theme: jekyll-theme-cayman

url: https://emkademy.com
author: Kıvanç Yüksel
title: Emkademy blog
motto: "Yerinde duran, geriye gidiyor demektir... İleri, daima ileri! - MKA"
description: "Interests of a Computer Scientist"
site_name: Emkademy
frame_image: "/assets/img/full_width_image.jpg"
host: 0.0.0.0
# avatar:

_: &kalkulus_oncesi_image "/assets/img/kalkulus_oncesi/kalkulus_oncesi.jpg"
_: &kalkulus_oncesi_title "Kalkülüs Öncesi"
_: &toolbox_image "/assets/img/toolbox/toolbox.jpg"
_: &toolbox_title "Toolbox"
_: &general_image "/assets/img/full_width_image.jpg"
_: &author1 "Kıvanç Yüksel"


defaults:
    - 
        scope:
            path: ""
        values:
            image: *general_image
            comments: true
    -
        scope:
            path: ""
            type: "kalkulus_oncesi"
        values:
            layout: "post"
            image: *kalkulus_oncesi_image
            author: *author1
    -
        scope:
            path: ""
            type: "toolbox"
        values:
            layout: "post"
            image: *toolbox_image
            author: *author1


collections_dir: my_collections
collections:
    kalkulus_oncesi:
        title: *kalkulus_oncesi_title
        image: *kalkulus_oncesi_image
        short_desc: "bla bla"
        group: "teorik_altyapi"
        permalink: /teorik_altyapi/:collection/:name
        output: true

    toolbox:
        title: *toolbox_title
        image: *toolbox_image
        short_desc: "bla bla"
        group: "research"
        permalink: /research/:collection/:name
        output: true

# algolia:
#   application_id: H33RL6BBPY
#   index_name:     emkademy
#   search_only_api_key: 2a2524980c465230715bba7cfc766e08

plugins:
    - jemoji
    - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed
  load_paths:
      - _sass
      - mdb_sass

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: kivancyy
  flickr:
  github: kivancyuksel
  instagram: kivancyuksell
  linkedin: kivanc-yuksel-6b7244150
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: kivanc_yuksel
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UC8QIX-TzWoF8CV9tgWYERqg
  googleplus: # anything in your profile username that comes after plus.google.com/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
